spring.application.name=CRUDOperations
server.port=8080
logging.level.org.springframework=INFO

#In memory database configuration
spring.datasource.url=jdbc:h2:mem:testDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Hibernate configuration
sprinh.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#to execute the ddl queries using the console
spring.h2.console.enabled=true
#path of console
spring.h2.console.path=/h2

spring.security.user.name=student
spring.security.user.password=student
